### ISSUE TITLE
return type of `is{Rev,Fwd}LimitSwitchClosed` is inconsistent between TalonFX and TalonSRX

### ISSUE THREAD

**Issue by ghost** [CrossTheRoadElec/Phoenix-Documentation#106]
This function returns an int with the TalonFX, and a boolean with the TalonSRX. These should both be booleans, why is it like this?

**Comment by JCaporuscio** [comment]
The `isLimitSwitchClosed` functions return an int in all cases, both for TalonSRX and TalonFX.

They're inherited from a BaseTalon parent class:
https://api.ctr-electronics.com/phoenix/release/java/com/ctre/phoenix/motorcontrol/can/BaseTalon.html#isFwdLimitSwitchClosed()
https://api.ctr-electronics.com/phoenix/release/java/com/ctre/phoenix/motorcontrol/can/BaseTalon.html#isRevLimitSwitchClosed()

Where are you seeing that the SRX version returns a boolean?

EDIT: Ah, I see where the confusion is.  The original SensorCollection implementation for SRX uses a boolean, before we standardized on using integers for digital input signals in Phoenix.

We may be able to change this in the future, though I do still recommend using the versions that are in the base class as opposed to SensorCollection.

**Comment by ghost** [comment]
Yeah, I was talking about the `getSensorCollection().is{Rev,Fwd}LimitSwitchClosed()`, didn't realize that this existed.

Thanks for the help.

By the way, "if" is misspelled there.

**Comment by auscompgeek** [comment]
> By the way, "if" is misspelled there.

Not a misspelling: https://en.wikipedia.org/wiki/If_and_only_if

**Comment by ghost** [comment]
> > By the way, "if" is misspelled there.
> 
> Not a misspelling: https://en.wikipedia.org/wiki/If_and_only_if

Interesting, didn't know that was a thing.
