### ISSUE TITLE
Link to new Firmware

### ISSUE THREAD

**Issue by team7116** [CrossTheRoadElec/Phoenix-Documentation#11]
I don't see where the new firmware is located. Is there a link on the web?

In my public documenst I only have the 2.00 version of the Talon SRX. I can't locate the new version.

**Comment by nix342** [comment]
The new version is installed with the new Phoenix Framework. The documentation with the location to find it is here:
https://github.com/CrossTheRoadElec/Phoenix-Documentation#update-your-can-devices

**Comment by JCaporuscio** [comment]
https://github.com/CrossTheRoadElec/Phoenix-Documentation#update-your-can-devices

Jacob Caporuscio
Software/Hardware Engineer
CTR Electronics

**Comment by ozrien** [comment]
Did you run the Phoenix installer?  Talon 2.0 is from two seasons ago.

**Comment by Tommsy64** [comment]
Download and run the CTRE Phoenix Framework Installer [here](http://www.ctr-electronics.com/control-system/hro.html#product_tabs_technical_resources). The firmware `.crf` files should be located in the `C:\Users\Public\Documents\Cross The Road Electronics\LifeBoat\HERO Firmware Files` folder.

**Comment by ozrien** [comment]
The firmware is on the site, installed on the PC, and doc'd in several places so closing the issue.
