### ISSUE TITLE
CANdle Animation Definition Documentation

### ISSUE THREAD

**Issue by dkt01** [CrossTheRoadElec/Phoenix-Documentation#110]
Is there any documentation on how to define a custom Animation class to control CANdle?  The abstract [`ctre::phoenix::led::Animation`](https://api.ctr-electronics.com/phoenix/release/cpp/classctre_1_1phoenix_1_1led_1_1_animation.html) (referencing release 5.21.2) doesn't seem to include any functions that control LED states to implement.

**Comment by JCaporuscio** [comment]
There is not, because defining a custom Animation in the API isn't really practical - each existing Animation is pre-defined and controlled in the firmware of the CANdle, the class is merely providing the animation parameters over CAN.

If you want to create animations by setting LED states from the API that's something that would have to be implemented manually.

**Comment by dkt01** [comment]
Thanks for the clarification.  Follow up question: [a comment in CANdleSystem.cpp:171 in the multi-animation example](https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/blob/ccbc278d944dae78c73b342003e65138934a1112/C%2B%2B%20General/CANdle-MultiAnimation/src/main/cpp/subsystems/CANdleSystem.cpp#L171) suggests that every call to `setLEDs()` sends a CAN frame.  Doing this on every individual LED could lead to very high bus load.  Is there any way to batch LED states (beyond sequential LEDs with the same color) to minimize bus utilization?  Something like a frame that updates 8-10 LEDs with a 4-byte (RGBW) state each utilizing the larger 64-byte CANFD frame size?  This could either be limited to sequential LEDs with a specified offset or be pairs of {address, RGBW} to support (possibly fewer but) random-access LED updates.  Then a user library could intelligently batch updates based on an animation definition.

**Comment by JCaporuscio** [comment]
It's correct that each `setLEDs()` call sends a CAN frame.
Setting multiple groups of LEDs to different colors in a single call isn't something that's supported right now - it's something we've discussed internally but isn't actively in development or on a roadmap yet.

**Comment by dkt01** [comment]
Alright.  I'm definitely interested in some additional APIs to provide users more efficient and advanced control over the device.  It's a really cool product and I look forward to exploring how far we can push it in our off season.
Thanks
