### ISSUE TITLE
TalonFX not mentioned

### ISSUE THREAD

**Issue by laviRZ** [CrossTheRoadElec/Phoenix-Documentation#113]
Why is it that in some places such as the `Motor Controller Closed Loop` only the Talon SRX and Victor SPX are mentioned to have that feature? What about the Talon FX?
This happens in a lot of other places as well.

**Comment by JCaporuscio** [comment]
This is likely just an oversight from when Talon FX was added to the motor controller line - it is not an intentional omission.
Any closed-loop feature that is present in both Victor SPX and Talon SRX is also present in Talon FX (in addition to FX-specific features as documented).
