### ISSUE TITLE
Ability to check limit switch status in code?

### ISSUE THREAD

**Issue by wrall** [CrossTheRoadElec/Phoenix-Documentation#17]
Could you please add an ability to check the current limit switch status for the forward and reverse limit switches?  It would be nice to have a function like getForwardLimitSwitchPressed() and getReverseLimitSwitchPressed() to show whether the forward/reverse limit switches are pressed or not.

It looks like the information is available but not currently exposed in the API.

**Comment by ozrien** [comment]
https://github.com/CrossTheRoadElec/Phoenix-Documentation/blob/master/Migration%20Guide.md

Search for "isFwdLimitSwitchClosed"

This is also useful if you just want to add some IO to the Talon (not necessarily for limit switch behavior).  Think of each Talon as an additional analog/digital/quad/pulse-width port so you don't have to hang every sensor off the RIO.

**Comment by wrall** [comment]
Ah, I see.  Perhaps that could be mentioned briefly in the main readme?

Thanks!

**Comment by JCaporuscio** [comment]
This is now mentioned in the main readme.

https://github.com/CrossTheRoadElec/Phoenix-Documentation/commit/708df6052cb71653078c4e04312bf04c39130701
