### ISSUE TITLE
Replacement for enableZeroSensorPositionOnForwardLimit()?

### ISSUE THREAD

**Issue by PChild** [CrossTheRoadElec/Phoenix-Documentation#19]
Is there a replacement for enableZeroSensorPositionOnForwardLimit() in Phoenix? We're manually zeroing right now, but couldn't find documentation on how to do it on the Talon only which would presumably be faster.

**Comment by JCaporuscio** [comment]
There's no API function right now, but you can use configSetParameter.

Use the eClearPositionOnLimitF parameter.  Pass in a value of 0 to disable the feature and a value of 1 to enable.  subValue and ordinal can be zero.

So the following would enable zeroing the sensor position on forward limit (with a timeout of 10 ms for the set):

talon.configSetParameter(ParamEnum.eClearPositionOnLimitF, 1, 0, 0, 10);

The same method can be used for clearing position on reverse limit or index.

**Comment by PChild** [comment]
Thanks for the help. Should that info go in the Migration Guide?

**Comment by ozrien** [comment]
Feature explanation and examples are available in the update software reference manual.

![image](https://user-images.githubusercontent.com/14191527/35162312-f766083e-fd10-11e7-8abd-f4e4e80a4486.png)

![image](https://user-images.githubusercontent.com/14191527/35162380-26c709f2-fd11-11e7-8513-2e8a58d523b6.png)


http://www.ctr-electronics.com/talon-srx.html#product_tabs_technical_resources or https://github.com/CrossTheRoadElec/Phoenix-Documentation
