### ISSUE TITLE
Talon current limiting documentation is unclear/inconsistent.

### ISSUE THREAD

**Issue by Oblarg** [CrossTheRoadElec/Phoenix-Documentation#25]
The current limiting documentation seems to be self-contradictory.

[The current-limiting section of the open-loop documentation](https://github.com/CrossTheRoadElec/Phoenix-Documentation#current-limiting) claims that current limiting only works in open-loop modes, and that closed-loop modes have their own current limiting API.

However, there is no section describing this API; the link to "current limiting" listed under the closed-loop section of the table of contents links to the previously-mentioned section in the the open-loop section of the documentation.

Do the current open-loop configuration methods work in closed-loop modes?  If so, the documentation should be fixed.  If they do not, then a section needs to be added explaining how to enable current limiting in closed-loop modes.

**Comment by ozrien** [comment]
Current limit functions in all modes.  README updated.
