### ISSUE TITLE
Question about Motion Magic Setup

### ISSUE THREAD

**Issue by ShreyaRavi** [CrossTheRoadElec/Phoenix-Documentation#28]
I was wondering if there's something wrong with the way I am setting up my program to use Motion Magic. (Just for some context, I am writing this in Java for my FRC robot.)

In `robotInit()`, I am calling the following methods:
`setInverted()` -- set to `false` (after testing)
`setSensorPhase()` -- set to `false` (after testing)
`configSelectedFeedbackSensor()` -- set to `FeedbackDevice.QuadEncoder`
`configNominalOutputForward()` -- set to `0`
`configNominalOutputReverse()` -- set to `0`
`configPeakOutputForward()` -- set to `1`
`configPeakOutputReverse()` -- set to `-1`
`setSelectedSensorPosition(0)`

and I set the PIDF values (still in `robotInit()`) using:
`config_kP()`
`config_kI()`
`config_kD()`
`config_kF()`
(all of the PID values are set to 0 initially and the Feed Forward Gain is calculated as discussed further below)

and I set the cruise velocity and acceleration (also in `robotInit()`) using:
`configMotionCruiseVelocity()`
`configMotionAcceleration()`

Then, in `teleopUpdate()`, I call the `set()` method as follows:
1. Calculate the number of native units to move forward --> `number_of_native_units`
2. Call `set(ControlMode.MotionMagic, number_of_native_units)`

I calculated the Feed Forward Gain as follows (using the Software Reference Manual's steps):
1. The maximum speed for the wheels (which are a geared output moving a ~120 lb load) was measured through testing to be 14.2 ft/s.
2. This was converted to revolutions per 100 ms on the motor output (which is what the encoder is attached to). 
I have the following specs on my setup:
Gear ratio = 8.45:1
Wheel Diameter = 6 in
Native Units per Revolution = 80
Time Period (As specified in documentation) = 100 ms

**Max Velocity in native units per time period:**
(14.2 ft/1 sec * 12 in/ft * 1 revolution/6π in * 8.45 * 80 native units/revolution * 1 sec/0.1 time periods)
= 611 units/time period

Feed-Forward Gain = (100% * 1023)/611 = **1.67**

In the documentation, it says to test with just this feed-forward gain.
______________________________________________________________________________________________________
**I will get to my problem now** (sorry the explanation to this point was so long):
In testing, this feed-forward did not actually move the wheels of the robot. In fact, the wheels only started to move once I drastically increased the feed-forward (from the calculated 1.67 to about 80).

And even in doing so, the feed-forward didn't actually move the wheels until about 5 or 6 seconds had passed. (I tested this by having the `set()` method only be called when I was holding down a button, as you did in the example.) 

The only difference I see between my code and the example code is that my setpoint is a constant and the example's setpoint is variable based on the joystick's value.

**What could be the source for my lag and what am I doing wrong for my calculated feed-forward value to be so unresponsive?**

Another thing that I found (and I don't know whether this is an issue or not) is that the closed loop feed forward does not actually start accumulating until several seconds had passed. **What could be the cause for this?**

**Comment by JCaporuscio** [comment]
This sounds like a support request.

Please send an e-mail to support@ctr-electronics.com.
In your e-mail, please describe the behavior you are seeing vs. what you are expecting.

**Comment by team6637** [comment]
Same Issue here! Any resolution?
