### ISSUE TITLE
Missing items from migration guide

### ISSUE THREAD

**Issue by sciencewhiz** [CrossTheRoadElec/Phoenix-Documentation#3]
Here are the items I had to change to get our 2017 code to compile with Phoenix, that were not already included in the migration guide.

setPID - replaced by individual config methods
getSetpoint - can't find replacement
getClosedLoopError - added parameter
getOutputVoltage - getMotorOutputVoltage
ControlMode - PercentVBus renamed PercentOutput and Speed renamed velocity.

**Comment by sciencewhiz** [comment]
Thanks for the update. Does this mean there isn't a replacement for getSetpoint?

**Comment by AaronPinto** [comment]
Also what about a replacement for setAllowableClosedLoopErr()?

**Comment by JCaporuscio** [comment]
@sciencewhiz Not currently.  A few people have asked for it back, so we're going to be adding it with this week's motion profile update.

@AaronPinto Apologies, it looks like it was missing from the migration guide.  It has been updated accordingly.

**Comment by NoMod-Programming** [comment]
Also, what happened to `setSafetyEnabled(boolean)` and `setClosedLoopOutputDirection(boolean)`?

**Comment by JCaporuscio** [comment]
@NoMod-Programming 
setSafetyEnabled is part of WPI_TalonSRX, as that is the class that implements WPI interfaces.
setClosedLoopOutputDirection is now in the migration guide.

@sciencewhiz We added getClosedLoopTarget in the latest release as a replacement for getSetpoint, and it is now documented in the migration guide.
