### ISSUE TITLE
Case of functions in Migration Guide doesn't match actual API.

### ISSUE THREAD

**Issue by Kython89** [CrossTheRoadElec/Phoenix-Documentation#8]
Example:
MigrationGuide: set, config
API: Set, Config

Not a huge deal but it is confusing to some students.

**Comment by JCaporuscio** [comment]
The convention for C++ is PascalCase, while the convention for Java is camelCase.

So whichever casing we document, it will be "wrong" for at least one of the languages.

**Comment by Kython89** [comment]
Thanks for the explanation.
