### ISSUE TITLE
Add link to Java/C++ javadocs to homepage

### ISSUE THREAD

**Issue by Daltz333** [CrossTheRoadElec/Phoenix-Documentation#94]
Finding the javadocs was quite difficult. It would be useful to add these to the homepage or sidebar.

**Comment by JCaporuscio** [comment]
Agreed.
There's some larger restructure that still needs to happen (see https://github.com/CrossTheRoadElec/Phoenix-Documentation/issues/78) but we should be able to split the API doc links out to be more obvious without waiting on that.

**Comment by ozrien** [comment]
Agreed.  
It's also listed here at the bottom:  https://store.ctr-electronics.com/software/

**Comment by Daltz333** [comment]
Yeah, I found that after someone pointed it out to me.

**Comment by JCaporuscio** [comment]
Just realized I never closed this - I added the C++/Java API docs links directly to the ToC tree so they should be easier to find.
https://github.com/CrossTheRoadElec/Phoenix-Documentation/commit/8ff6087ad3d43c6b0be74bac650a8cff93a12111
